---

- hosts: localhost
  tasks:
    - name: create directory for ssh-keys if doesn't exist
      file: path=files/keys state=directory
  tags: prepare


- hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Check if instances really got floating IPs
      when: hostvars[inventory_hostname].openstack.public_v4 == ''
      fail: msg="One of the instances didn't get floating IP address"
  tags: prepare



- hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait for ssh-server to start
      local_action:
        module: wait_for
          host="{{ hostvars[inventory_hostname].openstack.public_v4 }}"
          port=22
          search_regex=OpenSSH
          delay=3
          timeout=300
#    - debug: msg="Checking ssh for {{ hostvars[inventory_hostname].openstack.public_v4 }}"
  tags: prepare

- hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: install Python 2 if missing
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      delay: 10
  tags: prepare

- hosts: "{{ cluster_name }}_master"
  tasks:
    - name: generating key for hadoop user
      user: name={{ hadoop_user }} generate_ssh_key=yes
    - name: get the public key
      fetch: src="/home/{{ hadoop_user }}/.ssh/id_rsa.pub" dest="files/keys/{{ cluster_name }}.pub" flat=yes
    - name: get the private key
      fetch: src="/home/{{ hadoop_user }}/.ssh/id_rsa" dest="files/keys/{{ cluster_name }}" flat=yes

  tags: prepare

- hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  become: True
  become_user: root
  vars:
    hadoop_user: ubuntu
  tasks:
    - name: deploy authorized keys
      authorized_key: user={{ hadoop_user }} key={{ lookup('file', 'files/keys/{{ cluster_name }}.pub') }}

    - name: deploy ssh-keys
      copy: src="files/keys/{{ cluster_name }}" dest="/home/{{ hadoop_user }}/.ssh/{{ cluster_name }}"

    - name: distribute ssh config
      template: src=templates/config.j2 dest="/home/{{ hadoop_user }}/.ssh/config"

    - name: modify /etc/hosts
      lineinfile: dest=/etc/hosts state=present line="{{ hostvars[item].openstack.public_v4}} {{ hostvars[item].openstack.name }}"
      with_items: "{{ play_hosts }}"
    #  template: src=templates/hosts.j2 dest=/etc/hosts
  tags: prepare

- hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  become: True
  become_user: root
  tasks:
    - name: disable net.ipv6.conf.all.disable_ipv6
      sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present
      tags:
        - prepare

    - name: disable net.ipv4.tcp_syncookies
      sysctl: name=net.ipv4.tcp_syncookies value=1 state=present
      tags:
        - prepare

    - name: disable net.ipv4.conf.default.accept_source_route
      sysctl: name=net.ipv4.conf.default.accept_source_route value=0 state=present
      tags:
        - prepare

    - name: disable net.ipv4.tcp_tw_recycle
      sysctl: name=net.ipv4.tcp_tw_recycle value=1 state=present
      tags:
        - prepare

    - name: disable net.ipv4.ip_forward
      sysctl: name=net.ipv4.tcp_syncookies value=0 state=present
      tags:
        - prepare

    - name: disable net.ipv4.tcp_max_syn_backlog
      sysctl: name=net.ipv4.tcp_max_syn_backlog value=4096 state=present
      tags:
        - prepare

    - name: disable net.ipv4.conf.all.arp_filter
      sysctl: name=net.ipv4.conf.all.arp_filter value=1 state=present
      tags:
        - prepare

    - name: disable net.ipv4.ip_local_port_range
      sysctl: name=net.ipv4.ip_local_port_range value='1025 65535' state=present
      tags:
        - prepare

    - name: net.core.netdev_max_backlog
      sysctl: name=net.core.netdev_max_backlog value=10000 state=present
      tags:
        - prepare

    - name: net.core.rmem_max
      sysctl: name=net.core.rmem_max value=2097152 state=present
      tags:
        - prepare

    - name: net.core.wmem_max
      sysctl: name=net.core.wmem_max value=2097152 state=present
      tags:
        - prepare

    - name: vm.overcommit_memory
      sysctl: name=vm.overcommit_memory value=2 state=present
      tags:
        - prepare

    - name: kernel.shmmax
      sysctl: name=kernel.shmmax value=500000000 state=present
      tags:
        - prepare

    - name: kernel.shmmni
      sysctl: name=kernel.shmmni value=4096 state=present
      tags:
        - prepare

    - name: kernel.shmall
      sysctl: name=kernel.shmall value=4000000000 state=present
      tags:
        - prepare

    - name: kernel.sysrq
      sysctl: name=kernel.sem value=1 state=present
      tags:
        - prepare

    - name: kernel.sem
      sysctl: name=kernel.sem value='250 512000 100 2048' state=present
      tags:
        - prepare

    - name: disable net.ipv6.conf.lo.disable_ipv6
      sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 state=present
      tags:
        - prepare

    - name: increase hard file limits
      pam_limits: domain=* limit_type=hard limit_item=nofile value=unlimited
      tags:
        - prepare

    - name: increase proc hard limits
      pam_limits: domain=* limit_type=hard limit_item=nproc value=131072
      tags:
        - prepare

    - name: increase proc hard limits
      pam_limits: domain=* limit_type=soft limit_item=nproc value=131072
      tags:
        - prepare

    - name: increase soft file limits
      pam_limits: domain=* limit_type=soft limit_item=nofile value=unlimited

- name: "Install requisite software on nodes"
  hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  become: yes
  become_user: ubuntu
  tasks:
  - name: Install software
    script: "{{ playbook_dir }}/files/setup-nodes.sh"
